font_size      10
background_opacity 0.6
font_family      Monocraft Nerd Font


# --- Configuración de Colores Pasteles para Kitty ---

# Colores de fondo y texto (Base)
foreground            #CDD6F4
background            #1E1E2E
selection_foreground  #1E1E2E
selection_background  #F5E0DC

# Cursor
cursor                #F5E0DC
cursor_text_color     #1E1E2E

# La Paleta ANSI (0-15)

# Negro (Gris oscuro / Fondo suave)
color0  #45475A
color8  #585B70

# Rojo (Rosa Pastel / Coral)
color1  #F38BA8
color9  #F38BA8

# Verde (Menta / Sage)
color2  #A6E3A1
color10 #A6E3A1

# Amarillo (Crema / Trigo)
color3  #F9E2AF
color11 #F9E2AF

# Azul (Cielo / Lavanda)
color4  #89B4FA
color12 #89B4FA

# Magenta (Malva / Lila)
color5  #CBA6F7
color13 #CBA6F7

# Cian (Agua / Turquesa suave)
color6  #94E2D5
color14 #94E2D5

# Blanco (Texto suave / Nieve)
color7  #BAC2DE
color15 #A6ADC8
